### ISSUE TITLE
Rules Text too many columns (double double dot)

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/cardobject#60]
![image](https://user-images.githubusercontent.com/10943178/150634720-9933758f-35c6-41cc-970a-54dee2f7bd7f.png)

![image](https://user-images.githubusercontent.com/10943178/150634757-49e1d193-8ee4-4a29-9ee0-1e8c02d6faaa.png)

![image](https://user-images.githubusercontent.com/10943178/150634761-72e8a518-c97a-4b8d-9c80-6ff2addbf102.png)

**Comment by nlsui** [comment]
The Issue is not related to typos in the interaction text.
 Compare:
  - "Arrival: §Effects." -> no double column on card
  - "Pay §ManaAmount: §Effects." -> double column on card

Further testing showed that double columns get produced on Pay, DiscardPay and Dissolve which are all ability keywords that require a SimpleIntValue parameter. SimpleIntValue has no InteractionText itself so the additional column is propably not generated by the card grammar.

**Comment by patrickwieth** [comment]
fixed
