### ISSUE TITLE
Limit max. character numbers card names for 25 characters incl. spaces

### ISSUE THREAD

**Issue by AnnyBuh** [DecentralCardGame/cardobject#71]

**Comment by AnnyBuh** [comment]
Re-opening this as I am doing the design guidelines. Can we change the max. character numbers including spaces to 23?
25 is still too tightly squeezed. 

<img width="379" alt="Screenshot 2023-11-17 at 08 11 39" src="https://github.com/DecentralCardGame/cardobject/assets/48418575/e55319f3-c3d2-4446-89ed-dca2f224921a">
<img width="379" alt="Screenshot 2023-11-17 at 08 11 31" src="https://github.com/DecentralCardGame/cardobject/assets/48418575/327bd76d-a144-4fc6-8d33-9ae3be482cd5">

**Comment by patrickwieth** [comment]
From our current alpha set, only 2 carsds have more than 23 chars:

Time Manipulation Device
![image](https://github.com/DecentralCardGame/cardobject/assets/10943178/66fa46a5-2287-4535-a56d-54352f6d00fa)

Preserver of Lost Wisdom
![image](https://github.com/DecentralCardGame/cardobject/assets/10943178/713a1d28-7bc7-490e-b49e-2b1f3874aff8)

So we need to change those names. What I see here:
For these 2 cards it is not problematic and 24 chars is ok. I think the reason why your example looks squeezed is because these numbers take up more space than an average distribution of letters. The numbers are more like capital letters and most used letters take up a bit less space like a,e,u,o and especially i. 

So we have 3 options:
a) leave 25 chars as it is only a problem with names like THE BIG CHUNKY MONSTER WITH LONG NAME AND CAPSLOCK
b) change to 23, then we need to find new names for preserver of lost wisdom (can be changed to keeper easily) and Time Manipulation Device (not so easy, because other words like Apparatus, Gadget, Module are not really shorter). 
c) change to 24, we don't have to rename anything, we only have the trouble of updating the cardobject and deploying it

**Comment by patrickwieth** [comment]
Theoretically yes, but the problem is the cardobject has nothing todo with the svg textbox, maybe there is a mapping for the font how big letters are and we can use this in the cardobject. But the question is: Is it important enough for the amount of work?

**Comment by nlsui** [comment]
Answer: no.
decide on a lenght and I will set it to that
